### PR TITLE
sugarizer v1.1.0 + sugarizer-server dev branch on Node.js 8.x [FAILURE to reach MongoDB on RPi]

### PR DESCRIPTION
**Pull request by holta**
TEST PR based on PR #1430, to compare the latest Sugarizer on Node.js 8.x versus 10.x

Like PR #1430, it uses these sugarizer version "v1.1.0" and sugarizer-server branch "dev":
- https://github.com/llaske/sugarizer/releases/tag/v1.1.0
- https://github.com/llaske/sugarizer-server/tree/dev

### CODE REVIEW

**Comment by holta** [comment]
This modified/test PR (i.e. PR #1430 tweaked to work with Node.js 8.x instead of 10.x) works on Ubuntu 18.04 but not Raspbian/RPi!

_Is it possible sugarizer-server's dev branch does not work with Raspbian's MongoDB 2.4.14, whereas it does work with Ubuntu 18.04's MongoDB 3.6.3?_

In any case, when installing this modified/test PR, on Raspbian/RPi, the error was as follows:
```
root@box:~# journalctl -eu sugarizer | more
[...]
Feb 01 07:29:08 box.lan systemd[1]: sugarizer.service: Service hold-off time over, scheduling restart.
Feb 01 07:29:08 box.lan systemd[1]: Stopped Node.js Sugarizer Server.
Feb 01 07:29:08 box.lan systemd[1]: Started Node.js Sugarizer Server.
Feb 01 07:29:08 box.lan sugarizer[15442]: module.js:550
Feb 01 07:29:08 box.lan sugarizer[15442]:     throw err;
Feb 01 07:29:08 box.lan sugarizer[15442]:     ^
Feb 01 07:29:08 box.lan sugarizer[15442]: Error: Cannot find module 'express'
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Function.Module._resolveFilename (module.js:548:15)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Function.Module._load (module.js:475:25)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Module.require (module.js:597:17)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at require (internal/module.js:11:18)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Object.<anonymous> (/opt/iiab/sugarizer-server-dev/sugarizer.js:2:15)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Module._compile (module.js:653:30)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Object.Module._extensions..js (module.js:664:10)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Module.load (module.js:566:32)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at tryModuleLoad (module.js:506:12)
Feb 01 07:29:08 box.lan sugarizer[15442]:     at Function.Module._load (module.js:498:3)
Feb 01 07:29:08 box.lan systemd[1]: sugarizer.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 07:29:08 box.lan systemd[1]: sugarizer.service: Unit entered failed state.
Feb 01 07:29:08 box.lan systemd[1]: sugarizer.service: Failed with result 'exit-code'.
Feb 01 07:29:18 box.lan systemd[1]: sugarizer.service: Service hold-off time over, scheduling restart.
Feb 01 07:29:18 box.lan systemd[1]: Stopped Node.js Sugarizer Server.
Feb 01 07:29:18 box.lan systemd[1]: Started Node.js Sugarizer Server.
Feb 01 07:29:35 box.lan sugarizer[15463]: Waiting for DB...
Feb 01 07:29:36 box.lan sugarizer[15463]: Waiting for DB...
Feb 01 07:29:37 box.lan sugarizer[15463]: Waiting for DB...
[...]
```

**Comment by holta** [comment]
PR #1430 merged, so this one's no longer nec!
